const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..", "data", "leistungsscheine");

const DOMAIN_FOLDER = {
  migration: "01_migration",
  storage: "02_storage",
  network: "03_network",
  identity: "04_identity",
  security: "05_security",
  compute: "06_compute",
  databases: "07_databases",
  devops: "08_devops",
  management_governance: "09_management_governance",
  integration: "10_integration",
  monitoring_ops: "11_monitoring_ops",
  backup_dr: "12_backup_dr",
  change_enablement: "13_change_enablement",
  web_apps: "14_web_apps",
  vdi: "15_vdi",
};

function slugify(value) {
  return String(value || "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function defaults(spec) {
  return {
    id: spec.id,
    title: spec.title,
    domain: spec.domain,
    theme: spec.theme,
    summary: spec.summary,
    tags: spec.tags || ["Azure", spec.domain, spec.theme],
    source: {
      type: "manual",
      origin: "custom",
      url: spec.url || "",
    },
    estimate: {
      unit: "PT",
      min: spec.min,
      likely: spec.likely,
      max: spec.max,
    },
    intro: spec.intro || `Der Leistungsschein ${spec.id} adressiert den Teilbereich ${spec.theme}.`,
    services: spec.services || [
      "Workshop und Anforderungsabgleich",
      "Technische Umsetzung im abgestimmten Scope",
      "Review und Rueckspiegelung der Ergebnisse",
    ],
    deliverables: spec.deliverables || ["Ergebnisprotokoll", "Konfigurationsnachweis"],
    assumptions: spec.assumptions || [
      "Benannte Ansprechpartner stehen fuer Rueckfragen zur Verfuegung",
      "Zugaenge und Freigaben werden rechtzeitig bereitgestellt",
    ],
    constraints: spec.constraints || [
      "Aenderungen ausserhalb des Scopes werden separat abgestimmt",
      "Provider- und Drittanbietergrenzen koennen Laufzeiten beeinflussen",
    ],
    out_of_scope: spec.out_of_scope || [
      "Leistungen ausserhalb der beschriebenen Zielplattform",
      "Dauerhafter Betrieb ausserhalb vereinbarter Uebergabephase",
    ],
    acceptance: spec.acceptance || [
      "Abgestimmte Leistungen wurden nachvollziehbar umgesetzt",
      "Liefergegenstaende wurden uebergeben und geprueft",
    ],
    dependencies: {
      requires: spec.requires || [],
      excludes: spec.excludes || [],
    },
  };
}

const seedSpecs = [
  {
    id: "LS-1001",
    title: "Migrations-Kickoff & Scope-Abgleich",
    domain: "migration",
    theme: "fileserver-migration",
    summary: "Projektstart, Zielbildabgleich und gemeinsame Scope-Definition.",
    min: 1,
    likely: 2,
    max: 3,
    tags: ["Azure", "Migration", "Kickoff"],
  },
  {
    id: "LS-1002",
    title: "Quellanalyse Fileserver-Struktur",
    domain: "migration",
    theme: "fileserver-migration",
    summary: "Analyse von Datenvolumen, Shares, Dateitypen und Migrationsrisiken.",
    min: 2,
    likely: 4,
    max: 6,
    requires: ["LS-1001"],
    tags: ["Assessment", "Fileserver", "Migration"],
  },
  {
    id: "LS-1003",
    title: "Share-Struktur-Konzept Azure Files",
    domain: "storage",
    theme: "azure-files",
    summary: "Ziel-Share-Struktur inkl. Namenskonventionen und Segmentierung.",
    min: 1,
    likely: 3,
    max: 5,
    requires: ["LS-1002"],
    tags: ["Azure Files", "Design", "Storage"],
  },
  {
    id: "LS-1004",
    title: "NTFS-ACL Mapping Konzept",
    domain: "identity",
    theme: "acl-mapping",
    summary: "Mapping bestehender Berechtigungen auf Zielgruppen und Share-Ebenen.",
    min: 2,
    likely: 4,
    max: 7,
    requires: ["LS-1002"],
    tags: ["ACL", "Identity", "Berechtigungen"],
  },
  {
    id: "LS-1005",
    title: "Cutover-Planung & Runbook",
    domain: "migration",
    theme: "cutover",
    summary: "Cutover-Ablauf, Freeze-Fenster und Rollback-Entscheidungspunkte.",
    min: 2,
    likely: 3,
    max: 5,
    requires: ["LS-1002", "LS-1003", "LS-1004"],
    tags: ["Cutover", "Runbook", "Migration"],
  },
  {
    id: "LS-1006",
    title: "Hypercare 5 Werktage",
    domain: "change_enablement",
    theme: "hypercare",
    summary: "Stabilisierungsunterstuetzung mit Ticketsichtung und Tagesstatus.",
    min: 1,
    likely: 2,
    max: 3,
    requires: ["LS-1005"],
    excludes: ["LS-1007"],
    tags: ["Hypercare", "Support", "Go-Live"],
  },
  {
    id: "LS-1007",
    title: "Hypercare 10 Werktage",
    domain: "change_enablement",
    theme: "hypercare",
    summary: "Erweiterte Stabilisierung mit taeglichen Review-Slots.",
    min: 2,
    likely: 4,
    max: 6,
    requires: ["LS-1005"],
    excludes: ["LS-1006"],
    tags: ["Hypercare", "Support", "Operations"],
  },
  {
    id: "LS-1008",
    title: "Decommission On-Prem Fileserver",
    domain: "migration",
    theme: "decommission",
    summary: "Kontrollierte Abschaltung nach erfolgreicher Umstellung.",
    min: 1,
    likely: 2,
    max: 4,
    requires: ["LS-1005"],
    tags: ["Decommission", "Transition", "Fileserver"],
  },
  {
    id: "LS-1009",
    title: "Storage Account Baseline",
    domain: "storage",
    theme: "azure-storage",
    summary: "Provisionierung von Storage Account, RBAC und Basiskonfiguration.",
    min: 1,
    likely: 2,
    max: 4,
    requires: ["LS-1001"],
    tags: ["Storage Account", "Provisioning", "Azure"],
  },
  {
    id: "LS-1010",
    title: "Azure Files Shares Provisioning",
    domain: "storage",
    theme: "azure-files",
    summary: "Erstellung und Basiskonfiguration der File Shares.",
    min: 1,
    likely: 2,
    max: 4,
    requires: ["LS-1009", "LS-1003"],
    tags: ["Azure Files", "Provisioning"],
  },
  {
    id: "LS-1011",
    title: "Private Endpoint Setup",
    domain: "network",
    theme: "private-endpoint",
    summary: "Einrichtung von Private Endpoints fuer Storage-Zugriffe.",
    min: 1,
    likely: 2,
    max: 4,
    requires: ["LS-1009"],
    tags: ["Private Endpoint", "Network", "Security"],
  },
  {
    id: "LS-1012",
    title: "DNS Name Resolution fuer Private Endpoint",
    domain: "network",
    theme: "dns",
    summary: "DNS-Aufloesung fuer private Storage-Endpunkte absichern.",
    min: 1,
    likely: 2,
    max: 3,
    requires: ["LS-1011"],
    tags: ["DNS", "Private Endpoint", "Network"],
  },
  {
    id: "LS-1013",
    title: "Backup Policy Konfiguration",
    domain: "backup_dr",
    theme: "backup",
    summary: "Backup-Richtlinien fuer Azure Files definieren und aktivieren.",
    min: 1,
    likely: 2,
    max: 4,
    requires: ["LS-1010"],
    tags: ["Backup", "Azure Files", "Resilience"],
  },
  {
    id: "LS-1014",
    title: "Restore-Test (Datei/Ordner/Share)",
    domain: "backup_dr",
    theme: "restore-tests",
    summary: "Wiederherstellungsszenarien mit Protokoll und Lessons Learned.",
    min: 1,
    likely: 2,
    max: 3,
    requires: ["LS-1013"],
    tags: ["Restore", "Backup", "Test"],
  },
  {
    id: "LS-1015",
    title: "Monitoring Dashboard Azure Files",
    domain: "monitoring_ops",
    theme: "monitoring",
    summary: "Zentrale Metriken und Dashboards fuer Betriebsuebersicht.",
    min: 1,
    likely: 2,
    max: 4,
    requires: ["LS-1010"],
    tags: ["Monitoring", "Operations", "Azure Monitor"],
  },
  {
    id: "LS-1016",
    title: "Alerting-Regeln und Schwellenwerte",
    domain: "monitoring_ops",
    theme: "alerting",
    summary: "Alarmierungen fuer kritische Betriebsereignisse einrichten.",
    min: 1,
    likely: 2,
    max: 3,
    requires: ["LS-1015"],
    tags: ["Alerting", "Monitoring", "Operations"],
  },
  {
    id: "LS-1017",
    title: "Identity Integration (AD/Entra fuer Azure Files)",
    domain: "identity",
    theme: "azure-files-auth",
    summary: "Authentifizierungsweg fuer SMB-Zugriffe technisch bereitstellen.",
    min: 2,
    likely: 3,
    max: 5,
    requires: ["LS-1010"],
    tags: ["Identity", "Entra ID", "Azure Files"],
  },
  {
    id: "LS-1018",
    title: "RBAC und Zugriffs-Governance",
    domain: "management_governance",
    theme: "rbac-governance",
    summary: "Rollenmodell und Zugriffsgovernance fuer den Service definieren.",
    min: 1,
    likely: 2,
    max: 4,
    requires: ["LS-1017"],
    tags: ["RBAC", "Governance", "Security"],
  },
  {
    id: "LS-1019",
    title: "Storage Security Hardening",
    domain: "security",
    theme: "hardening",
    summary: "Sicherheitsbaseline fuer Storage, Protokolle und Zugriffspfade.",
    min: 1,
    likely: 3,
    max: 5,
    requires: ["LS-1009", "LS-1011"],
    tags: ["Hardening", "Security", "Storage"],
  },
  {
    id: "LS-1020",
    title: "Defender for Storage Aktivierung",
    domain: "security",
    theme: "defender",
    summary: "Sicherheitsanalysen und Basisschutz fuer Storage-Ressourcen.",
    min: 1,
    likely: 2,
    max: 4,
    requires: ["LS-1019"],
    tags: ["Defender", "Security", "Storage"],
  },
  {
    id: "LS-1021",
    title: "FinOps Guardrails fuer Storage-Kosten",
    domain: "management_governance",
    theme: "finops",
    summary: "Kostenleitplanken, Budgetwarnungen und Nutzungsgrenzen definieren.",
    min: 1,
    likely: 2,
    max: 3,
    requires: ["LS-1009"],
    tags: ["FinOps", "Governance", "Cost"],
  },
  {
    id: "LS-1022",
    title: "Landing Zone Light Setup",
    domain: "management_governance",
    theme: "landing-zone",
    summary: "Grundlegende Subscription-/Resource-Group-Struktur inkl. Policies.",
    min: 2,
    likely: 4,
    max: 6,
    requires: ["LS-1001"],
    tags: ["Landing Zone", "Governance", "Azure"],
  },
  {
    id: "LS-1023",
    title: "IaC Pipeline (Bicep/Terraform) fuer Files-Plattform",
    domain: "devops",
    theme: "iac",
    summary: "Automatisierte Bereitstellung und Aenderungsnachvollziehbarkeit.",
    min: 2,
    likely: 4,
    max: 7,
    requires: ["LS-1022"],
    tags: ["IaC", "DevOps", "Automation"],
  },
  {
    id: "LS-1024",
    title: "ITSM Betriebsuebergabe",
    domain: "change_enablement",
    theme: "itsm-handover",
    summary: "Runbooks, Ticketprozesse und Betriebsuebergabe in den Regelbetrieb.",
    min: 1,
    likely: 3,
    max: 5,
    requires: ["LS-1015"],
    tags: ["ITSM", "Transition", "Operations"],
  },
  {
    id: "LS-1025",
    title: "Pilot-Rollout Begleitung",
    domain: "change_enablement",
    theme: "pilot",
    summary: "Gestaffelter Pilot mit Feedbackschleife und Nachsteuerung.",
    min: 2,
    likely: 3,
    max: 5,
    requires: ["LS-1005"],
    tags: ["Pilot", "Change", "Adoption"],
  },
  {
    id: "LS-1026",
    title: "Nutzerkommunikation & Kurzschulung",
    domain: "change_enablement",
    theme: "enablement",
    summary: "Nutzerleitfaden, Kommunikationsbausteine und FAQ fuer Umstellung.",
    min: 1,
    likely: 2,
    max: 4,
    requires: ["LS-1005"],
    tags: ["Enablement", "Training", "Communication"],
  },
  {
    id: "LS-1027",
    title: "App Service Basisplattform",
    domain: "web_apps",
    theme: "app-service",
    summary: "Basisbereitstellung fuer Web-Workloads auf Azure App Service.",
    min: 2,
    likely: 3,
    max: 6,
    tags: ["App Service", "Web", "Compute"],
  },
  {
    id: "LS-1028",
    title: "Azure SQL Betriebsgrundlagen",
    domain: "databases",
    theme: "azure-sql",
    summary: "Basiskonfiguration von Azure SQL inkl. Security und Monitoring-Anbindung.",
    min: 2,
    likely: 4,
    max: 7,
    tags: ["Azure SQL", "Database", "Security"],
  },
  {
    id: "LS-1029",
    title: "Azure Virtual Desktop Readiness",
    domain: "vdi",
    theme: "azure-virtual-desktop",
    summary: "Readiness und Zielarchitektur fuer AVD-Anwendungsfall.",
    min: 2,
    likely: 4,
    max: 6,
    tags: ["AVD", "VDI", "Assessment"],
  },
  {
    id: "LS-1030",
    title: "Logic Apps Integrationsbaustein",
    domain: "integration",
    theme: "logic-apps",
    summary: "Integrationsworkflow fuer Datei-/Event-Prozesse konzipieren und implementieren.",
    min: 2,
    likely: 3,
    max: 6,
    tags: ["Logic Apps", "Integration", "Automation"],
  },
];

function writeSeed(spec) {
  const module = defaults(spec);
  const folder = DOMAIN_FOLDER[module.domain];
  if (!folder) {
    throw new Error(`No folder mapping for domain ${module.domain} (${module.id})`);
  }
  const themeSlug = slugify(module.theme);
  const titleSlug = slugify(module.title);
  const targetDir = path.join(ROOT, folder, themeSlug);
  fs.mkdirSync(targetDir, { recursive: true });
  const fileName = `${module.id}__${titleSlug}.json`;
  const targetFile = path.join(targetDir, fileName);
  fs.writeFileSync(targetFile, `${JSON.stringify(module, null, 2)}\n`, "utf8");
}

function main() {
  fs.rmSync(ROOT, { recursive: true, force: true });
  fs.mkdirSync(ROOT, { recursive: true });
  seedSpecs.forEach(writeSeed);
  console.log(`Seed-Leistungsscheine erzeugt: ${seedSpecs.length}`);
}

if (require.main === module) {
  main();
}
